# WP Engine Atlas deployment configuration for Mastra Deep Research template
name: mastra-deep-research
type: nodejs:20

# Build and deploy configuration
build:
  flavor: none

# Web configuration
web:
  commands:
    start: "npm start"
  upstream:
    socket_family: tcp
    protocol: http
    timeout: 300  # 5 minutes for long-running operations
    keepalive_timeout: 300  # Keep connections alive for long operations
  locations:
    /:
      passthru: true
      request_timeout: 300  # 5 minutes for API requests
      response_timeout: 300  # 5 minutes for response
      fastcgi_read_timeout: 300  # FastCGI timeout
    /api:
      passthru: true
      request_timeout: 300  # Extended timeout for API routes
      response_timeout: 300
      fastcgi_read_timeout: 300

# Persistent storage for database and uploads
disk: 2048

mounts:
  "/storage":
    source: local
    source_path: storage

# Environment variables (set these in Atlas dashboard)
variables:
  env:
    NODE_ENV: "production"
    # OPENAI_API_KEY: "your_openai_api_key_here"
    # EXASEARCH_API_KEY: "your_exa_api_key_here"
    # DATABASE_URL: "file:./storage/mastra.db"

# Dependencies and build process
dependencies:
  nodejs:
    npm: "*"

hooks:
  build: |
    npm ci --include=dev
    npm run build
  deploy: |
    echo "Mastra Deep Research deployed successfully"

# Health check
health:
  path: "/"
  timeout: 30
  interval: 10